<?php



/**



 * @version     $Id$ 2.0.0 0



 * @package     Joomla



 * @copyright   Copyright (C) 2005 - 2008 Open Source Matters. All rights reserved.



 * @license     GNU/GPL, see LICENSE.php



 */







// no direct access



defined('_JEXEC') or die('Restricted access');







// the instruction will be added here



?>



<div id="aiContactSafe_help_file">



<h4>Campos</h4>



<p>Aquí es donde usted puede administrar sus campos personalizados.</p>



Use la barra de herramientas arriba a la derecha para Agregar / Modificar / Borrar / Publicar / Despublicar campos.<br/>



Todos estos botones ( excepto <strong><?php echo JText::_( 'Add new' ); ?></strong> ) pueden usarse sólo después de que al menos un campo es seleccionado de la lista de campos.<br />



Usted puede seleccionar uno o más campos haciendo click en el checkbox a la izquierda del nombre del campo. Haga click en el checkbox superior para seleccionar todos los campos en esta página.<br />



<br/>



Haga click en el nombre del campo para editarlo.<br/>



<br/>



Ingrese un nombre parcial/total de un campo en la casilla de texto colocada arriba de la lista de campos y haga click a  <strong><?php echo JText::_( 'Go' ); ?></strong> para filtrar los campos. Haga click a <strong><?php echo JText::_( 'Reset' ); ?></strong> para remover los filtros.<br/>



<br/>



Haga click en la <strong>cabecera</strong> de cualquier columna para modificar el orden en que se presenta la lista.<br/>



<br/>



</div>



